### ISSUE TITLE
[cgjs-solns] tictactoe/ui.js: Function within a loop

### ISSUE THREAD

**Issue by wei2912** [wei2912/cgjs#10]
From line 87 to 92, a function was created inside a loop. Shouldn't this be avoided?

For obvious reasons I won't quote the code.

**Comment by bnjmnt4n** [comment]
This doesn't seem to exist anymore, unless you're referring to lines 70 to 75, where the function is a function expression and not a function declaration, thus it can be used in a loop without issues (and is used to create a closure).
