### ISSUE TITLE
Rename repo?

### ISSUE THREAD

**Issue by bnjmnt4n** [wei2912/cgjs#3]
Since you've already deleted it, why not rename it? If you rename using GitHub, the links should redirect, so shortlinks should still work.

**Comment by wei2912** [comment]
Ooh. I wanted to do that, but forgot about it.

**Comment by wei2912** [comment]
Renamed to `cgjs`.

**Comment by wei2912** [comment]
Hmm. https://wei2912.github.io/gamedesign-js/ doesn't work anymore. May have to regenerate the short links.
